function TestData() {
  return new Map([
    [("Name", "Bloodstained Mire")],
    [("Name", "Command Tower")],
    [("Name", "Fabled Passage")],
    [("Name", "Flooded Strand")],
    [("Name", "Great Furnace")],
    [("Name", "Island")],
    [("Name", "Mountain")],
    [("Name", "Mystic Sanctuary")],
    [("Name", "Polluted Delta")],
    [("Name", "Seat of the Synod")],
    [("Name", "Steam Vents")],
    [("Name", "Sulfur Falls")],
    [("Name", "Temple of the False God")],
    [("Name", "Wooded Foothills")],
    [("Name", "Anticipate")],
    [("Name", "Arcane Signet")],
    [("Name", "Argentum Armor")],
    [("Name", "Armory Automaton")],
    [("Name", "Basilisk Collar")],
    [("Name", "Batterskull")],
    [("Name", "Bloodforged Battle-Axe")],
    [("Name", "Brainstorm")],
    [("Name", "Brass Squire")],
    [("Name", "Chaos Warp")],
    [("Name", "Counterspell")],
    [("Name", "Cyclonic Rift")],
    [("Name", "Dalakos, Crafter of Wonders")],
    [("Name", "Deadeye Quartermaster")],
    [("Name", "Divination")],
    [("Name", "Dramatic Reversal")],
    [("Name", "Echo Storm")],
    [("Name", "Emry, Lurker of the Loch")],
    [("Name", "Etherium Sculptor")],
    [("Name", "Fabricate")],
    [("Name", "Foundry Inspector")],
    [("Name", "Goblin Engineer")],
    [("Name", "Hammer of Nazahn")],
    [("Name", "Herald of Kozilek")],
    [("Name", "Isochron Scepter")],
    [("Name", "Izzet Signet")],
    [("Name", "Jhoira, Weatherlight Captain")],
    [("Name", "Kazuul's Toll Collector")],
    [("Name", "Mask of Memory")],
    [("Name", "Mind Stone")],
    [("Name", "Mirran Spy")],
    [("Name", "Mirrormade")],
    [("Name", "Mystic Repeal")],
    [("Name", "Narset's Reversal")],
    [("Name", "Negate")],
    [("Name", "Nettle Drone")],
    [("Name", "Neurok Stealthsuit")],
    [("Name", "Rapid Hybridization")],
    [("Name", "Reality Shift")],
    [("Name", "Rhystic Study")],
    [("Name", "Saheeli, Sublime Artificer")],
    [("Name", "Saheeli, the Gifted")],
    [("Name", "Sai, Master Thopterist")],
    [("Name", "Scytheclaw")],
    [("Name", "Shadowspear")],
    [("Name", "Skullclamp")],
    [("Name", "Sol Ring")],
    [("Name", "Solemn Simulacrum")],
    [("Name", "Swan Song")],
    [("Name", "Sword of Feast and Famine")],
    [("Name", "Sword of the Animist")],
    [("Name", "Talisman of Creativity")],
    [("Name", "Tezzeret the Seeker")],
    [("Name", "Tezzeret, Artifice Master")],
    [("Name", "Thopter Spy Network")],
    [("Name", "Thoughtcast")],
    [("Name", "Trailblazer's Boots")],
    [("Name", "Trinket Mage")],
    [("Name", "Trophy Mage")],
    [("Name", "Unwinding Clock")],
    [("Name", "Vandalblast")],
    [("Name", "Vedalken Engineer")],
    [("Name", "Zephyr Scribe")]
  ]);
}

export default TestData;
